#!/usr/bin/env bash

USER_COUNT=10
echo "Removing ${USER_COUNT} previously added dummy users"

for (( k=0; k<=$USER_COUNT; k++ )); do
  userdel omogenexec-user$k&
done
wait
userdel omogenexec-user
groupdel omogenexec-users
