#!/usr/bin/env bash

USER_COUNT=10
echo "Adding ${USER_COUNT} dummy users"
mkdir -p /var/lib/omogen/sandbox/
groupadd --system omogenexec-users
useradd --system omogenexec-user -G omogenexec-users
for (( k=0; k<=$USER_COUNT; k++ )); do
  # adduser doesn't fail if the user already exists
  useradd --system omogenexec-user$k -G omogenexec-users&
done
wait

chmod u+s /usr/bin/omogenexec
chmod u+s /usr/bin/omogenexec-fixpermissions
